//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoGoBot.Console.Resources.Languages.Console {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoGoBot.Console.Resources.Languages.Console.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticated.
        /// </summary>
        internal static string Bot_Authenticated {
            get {
                return ResourceManager.GetString("Bot_Authenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press {0} to exit.
        /// </summary>
        internal static string Bot_Exit_Info {
            get {
                return ResourceManager.GetString("Bot_Exit_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting now.
        /// </summary>
        internal static string Bot_Exit_Now {
            get {
                return ResourceManager.GetString("Bot_Exit_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bot.
        /// </summary>
        internal static string Bot_Identifier {
            get {
                return ResourceManager.GetString("Bot_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the accounts file.
        /// </summary>
        internal static string Bot_Load_Accounts_Error {
            get {
                return ResourceManager.GetString("Bot_Load_Accounts_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New accounts file created, please edit it to your likings and restart the application.
        /// </summary>
        internal static string Bot_Load_Accounts_New {
            get {
                return ResourceManager.GetString("Bot_Load_Accounts_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded accounts.
        /// </summary>
        internal static string Bot_Load_Accounts_Success {
            get {
                return ResourceManager.GetString("Bot_Load_Accounts_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load the settings file.
        /// </summary>
        internal static string Bot_Load_Settings_Error {
            get {
                return ResourceManager.GetString("Bot_Load_Settings_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New settings file created, please edit it to your likings and restart the application.
        /// </summary>
        internal static string Bot_Load_Settings_New {
            get {
                return ResourceManager.GetString("Bot_Load_Settings_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded settings.
        /// </summary>
        internal static string Bot_Load_Settings_Success {
            get {
                return ResourceManager.GetString("Bot_Load_Settings_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Bot_Started {
            get {
                return ResourceManager.GetString("Bot_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terminated.
        /// </summary>
        internal static string Bot_Terminated {
            get {
                return ResourceManager.GetString("Bot_Terminated", resourceCulture);
            }
        }
    }
}
