//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoGoBot.Console.Resources.Languages.Logic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoGoBot.Console.Resources.Languages.Logic.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PokeStop.
        /// </summary>
        internal static string Task_Fort_PokeStop_Identifier {
            get {
                return ResourceManager.GetString("Task_Fort_PokeStop_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | XP {1} | {2}.
        /// </summary>
        internal static string Task_Fort_PokeStop_Message {
            get {
                return ResourceManager.GetString("Task_Fort_PokeStop_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recycle.
        /// </summary>
        internal static string Task_Item_Recycle_Identifier {
            get {
                return ResourceManager.GetString("Task_Item_Recycle_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        internal static string Task_Item_Recycle_Message {
            get {
                return ResourceManager.GetString("Task_Item_Recycle_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string Task_Item_Use_Identifier {
            get {
                return ResourceManager.GetString("Task_Item_Use_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} x {1}.
        /// </summary>
        internal static string Task_Item_Use_Message {
            get {
                return ResourceManager.GetString("Task_Item_Use_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LevelUp Rewards.
        /// </summary>
        internal static string Task_Player_LevelUpRewards_Identifier {
            get {
                return ResourceManager.GetString("Task_Player_LevelUpRewards_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} | {1}.
        /// </summary>
        internal static string Task_Player_LevelUpRewards_Message_Detected {
            get {
                return ResourceManager.GetString("Task_Player_LevelUpRewards_Message_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Softban.
        /// </summary>
        internal static string Task_Player_Softban_Identifier {
            get {
                return ResourceManager.GetString("Task_Player_Softban_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        internal static string Task_Player_Softban_Message_Detected {
            get {
                return ResourceManager.GetString("Task_Player_Softban_Message_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypassed.
        /// </summary>
        internal static string Task_Player_Softban_Message_Lifted {
            get {
                return ResourceManager.GetString("Task_Player_Softban_Message_Lifted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Update.
        /// </summary>
        internal static string Task_Player_Update_Identifier {
            get {
                return ResourceManager.GetString("Task_Player_Update_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string Task_Player_Update_Message {
            get {
                return ResourceManager.GetString("Task_Player_Update_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pokemon.
        /// </summary>
        internal static string Task_Pokemon_Catch_Identifier {
            get {
                return ResourceManager.GetString("Task_Pokemon_Catch_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} | {1} | CP {2} | Chance: {3}%.
        /// </summary>
        internal static string Task_Pokemon_Catch_Message {
            get {
                return ResourceManager.GetString("Task_Pokemon_Catch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evolve.
        /// </summary>
        internal static string Task_Pokemon_Evolve_Identifier {
            get {
                return ResourceManager.GetString("Task_Pokemon_Evolve_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (CP {1}).
        /// </summary>
        internal static string Task_Pokemon_Evolve_Message {
            get {
                return ResourceManager.GetString("Task_Pokemon_Evolve_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        internal static string Task_Pokemon_Release_Identifier {
            get {
                return ResourceManager.GetString("Task_Pokemon_Release_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (CP {1}) (XP {2}) (IA {3}) (ID {4}) (IS {5}).
        /// </summary>
        internal static string Task_Pokemon_Release_Message {
            get {
                return ResourceManager.GetString("Task_Pokemon_Release_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route Next Point.
        /// </summary>
        internal static string Task_Route_Next_Point_Identifier {
            get {
                return ResourceManager.GetString("Task_Route_Next_Point_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) {1} {2}.
        /// </summary>
        internal static string Task_Route_Next_Point_Message {
            get {
                return ResourceManager.GetString("Task_Route_Next_Point_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Egg Incubator.
        /// </summary>
        internal static string Task_Use_Item_Egg_Incubator_Identifier {
            get {
                return ResourceManager.GetString("Task_Use_Item_Egg_Incubator_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0}) {1} {2}.
        /// </summary>
        internal static string Task_Use_Item_Egg_Incubator_Message {
            get {
                return ResourceManager.GetString("Task_Use_Item_Egg_Incubator_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Lucky Egg.
        /// </summary>
        internal static string Task_Use_Lucky_Egg_Identifier {
            get {
                return ResourceManager.GetString("Task_Use_Lucky_Egg_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string Task_Use_Lucky_Egg_Message {
            get {
                return ResourceManager.GetString("Task_Use_Lucky_Egg_Message", resourceCulture);
            }
        }
    }
}
